mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
context:
    data:
        site_title: Transparência Hacker
        author:
            name: THacker
            url: "http://thacker.com.br"
        google_analytics_id: UA-XXXXX-YY
        home_url: index.html
        menu:
            - title: Projetos
              url: /projects/index.html
            - title: Pessoas
              url: /people/index.html

meta:
    charset: "utf-8"
    nodemeta: meta.yaml
sorter:
    title:
        attr:
            - meta.title
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
